### ISSUE TITLE
.

### ISSUE THREAD

**Issue by nano-roni** [j4velin/chess#1]

**Comment by j4velin** [comment]
In the Google Developer Console (https://console.developers.google.com) you need to enable the APIs:

Google Play Game Management  
Google Play Game Services  
Google+ API

Not quite sure if that's the issue though

**Comment by nano-roni** [comment]
still didnt helped,any other ideas?

2015-03-03 14:24 GMT+02:00 Thomas Hoffmann <notifications@github.com>:

**Comment by nano-roni** [comment]
it was allready been activated, so i dont know what is the cause off  it,
what version are you using of google play service lib?
or maybe there is some lib i forgot to add to dependencies.
thanks

2015-03-03 17:58 GMT+02:00 Nano Crysis <nanowarcraft2@gmail.com>:

**Comment by nano-roni** [comment]
hi again, sorry i am driving you crazy with this again, i just want it to
work so badly, i have a pic that i get requests when i login in the account
picker, but there is showing some errors with that requests in the pic i
send you, how do i check this errors? or maybe can you send me your
4playerchess project that worked with you, thanks again and sorry for my
bad english.

2015-03-03 8:14 GMT-08:00 Nano Crysis <nanowarcraft2@gmail.com>:

**Comment by nano-roni** [comment]
as you can see in the pic i did the instruction of google play game service
right, so i see that requests, but after i login in the account picker,
when i click on something is shows me the account picker again, like it
wosent connected , always ask to connect no matter what i do.

2015-03-22 7:45 GMT-07:00 Nano Crysis <nanowarcraft2@gmail.com>:

**Comment by nano-roni** [comment]
please check what i wrote to you in your chess project issues on github.
thanks.

**Comment by j4velin** [comment]
Sorry, I dont see any picture. I'm sorry, I can't really give you any support on Google related products. The code you're seeing in the repo is the actual project code I'm using
